### PR TITLE
Animated mosaic

### PR DESCRIPTION
**Pull request by ndahlquist**
This adds a gif of the mosaic to the readme, as well as the script to generate it (thanks @JasonOrozcoLeiaInc!).

You can see an demo of this in the readme here:

https://github.com/LeiaInc/holopix50k/blob/ad47169186358f81343b941cb95a29cd52d6035e/README.md

Note: I didn't have the original 'target' image, so I made a new one. Happy to swap it out for the original if someone has it.

### CODE REVIEW

**Comment by PuneetKohli** [comment]
image
^ This was the original target (with a simplified version of Holopix logo ontop). 
@JasonOrozcoLeiaInc Do you have the one we actually used?

**Comment by JasonOrozcoLeiaInc** [comment]
I have a lot of different target images. We would have to check the windows desktop that generated it to see which target was last used. Assuming the script wasn't changed further.

**Comment by ndahlquist** [comment]
@PuneetKohli @JasonOrozcoLeiaInc I've removed the script and swapped out Puneet's updated gif. Do we feel that we need to replicate the original image? If so I just need the "simplified version of the Holopix logo". Also I modified the script to choose the nearest color in a different way, so probably the output will look different.

**Comment by JasonOrozcoLeiaInc** [comment]
I like that this version has the logo's highlights and shadows in it. Not sure if an unfamiliar eye would see it that way though.

**Comment by PuneetKohli** [comment]
I like both versions, and we can use both as we need.

Here is the simplified logo:
image

We can try generating something similar to the original mosaic with the new script and might as well keep both on the Repo?

**Comment by PuneetKohli** [comment]
Also super-imposed the two images based on the same height ratio as our final mosaic: 
image

**Comment by ndahlquist** [comment]
Thanks Puneet, I'll try generating this one now

**Comment by ndahlquist** [comment]
out

**Comment by ndahlquist** [comment]
This one is with L2(RGB), as Jason originally had it:

out

I think the contrast is not as good as the original image, maybe related to the removal of the foreground/background logic?

**Comment by ndahlquist** [comment]
I prefer the original gif:

mosaic

**Comment by PuneetKohli** [comment]
Possibly, lets stick with the one from this PR. Thanks for taking a stab at generating the GIF based on our original mosaic though!

**Pull request merged**
